import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();

  const { data } = api.poems.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {user.isSignedIn && <SignOutButton />}
        {!user.isSignedIn && <SignInButton />}
        <div>
          {data?.map((p) => (
            <div key={p.id}>
              <div>{p.title}</div>
              <div>{p.content}</div>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
