import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();

  const { data } = api.poems.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen">
        {user.isSignedIn && <SignOutButton />}

        {!user.isSignedIn && (
          <div className="flex h-full w-full flex-col items-center justify-center">
            <h1 className="p-4 text-4xl">Welcome to LyricLabs</h1>
            <h3 className="text-xl">Your poetry writing assistant</h3>
            <div className="p-8">
              <button className="rounded bg-slate-200 p-2">
                <SignInButton />
              </button>
            </div>
            <h3>TODO: render poems nicely</h3>
            {data?.map((p) => (
              <div key={p.id}>
                <div>{p.title}</div>
                <div>{p.content}</div>
              </div>
            ))}
          </div>
        )}
        <div></div>
      </main>
    </>
  );
};

export default Home;
